
export const INFERIORADULTO = [
  {
    cod: 'd48',
    nom: '4.8',
    img_sano: 'assets/images/pages/dientes/d4/d48/diag/d48.png',
    img_endodoncia: 'assets/images/pages/dientes/d4/d48/diag/e_d48.png',
    img_endodonciap: 'assets/images/pages/dientes/d4/d48/diag/ep_d48.png',
    img_extraccion: 'assets/images/pages/dientes/d4/d48/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d4/d48/diag/c_d48.png',
    img_implante: 'assets/images/pages/dientes/d4/d48/diag/i_d48.png',
    img_lesion: 'assets/images/pages/dientes/d4/d48/diag/lc_d48.png',
    img_pulpotomia: 'assets/images/pages/dientes/d4/d48/diag/p_d48.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d4/d48/diag/pp_d48.png',
    img_coronaacero: 'assets/images/pages/dientes/d4/d48/diag/cai_d48.png',
    img_coronaacetato: 'assets/images/pages/dientes/d4/d48/diag/ca_d48.png',
    img_fluoruro: 'assets/images/pages/dientes/d4/d48/diag/fp_d48.png',
    img_pulpectomia: 'assets/images/pages/dientes/d4/d48/diag/pul_d48.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d4/d48/diag/pulp_d48.png',

    img_dientepilar: 'assets/images/pages/dientes/d4/d48/diag/dp_d48.png',
    img_protesisp: 'assets/images/pages/dientes/d4/d48/diag/pp.png',
  },
  {
    cod: 'd47',
    nom: '4.7',
    img_sano: 'assets/images/pages/dientes/d4/d47/diag/d47.png',
    img_endodoncia: 'assets/images/pages/dientes/d4/d47/diag/e_d47.png',
    img_endodonciap: 'assets/images/pages/dientes/d4/d47/diag/ep_d47.png',
    img_extraccion: 'assets/images/pages/dientes/d4/d47/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d4/d47/diag/c_d47.png',
    img_implante: 'assets/images/pages/dientes/d4/d47/diag/i_d47.png',
    img_lesion: 'assets/images/pages/dientes/d4/d47/diag/lc_d47.png',
    img_pulpotomia: 'assets/images/pages/dientes/d4/d47/diag/p_d47.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d4/d47/diag/pp_d47.png',
    img_coronaacero: 'assets/images/pages/dientes/d4/d47/diag/cai_d47.png',
    img_coronaacetato: 'assets/images/pages/dientes/d4/d47/diag/ca_d47.png',
    img_fluoruro: 'assets/images/pages/dientes/d4/d47/diag/fp_d47.png',
    img_pulpectomia: 'assets/images/pages/dientes/d4/d47/diag/pul_d47.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d4/d47/diag/pulp_d47.png',

    img_dientepilar: 'assets/images/pages/dientes/d4/d47/diag/dp_d47.png',
    img_protesisp: 'assets/images/pages/dientes/d4/d47/diag/pp.png',
  },
  {
    cod: 'd46',
    nom: '4.6',
    img_sano: 'assets/images/pages/dientes/d4/d46/diag/d46.png',
    img_endodoncia: 'assets/images/pages/dientes/d4/d46/diag/e_d46.png',
    img_endodonciap: 'assets/images/pages/dientes/d4/d46/diag/ep_d46.png',
    img_extraccion: 'assets/images/pages/dientes/d4/d46/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d4/d46/diag/c_d46.png',
    img_implante: 'assets/images/pages/dientes/d4/d46/diag/i_d46.png',
    img_lesion: 'assets/images/pages/dientes/d4/d46/diag/lc_d46.png',
    img_pulpotomia: 'assets/images/pages/dientes/d4/d46/diag/p_d46.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d4/d46/diag/pp_d46.png',
    img_coronaacero: 'assets/images/pages/dientes/d4/d46/diag/cai_d46.png',
    img_coronaacetato: 'assets/images/pages/dientes/d4/d46/diag/ca_d46.png',
    img_fluoruro: 'assets/images/pages/dientes/d4/d46/diag/fp_d46.png',
    img_pulpectomia: 'assets/images/pages/dientes/d4/d46/diag/pul_d46.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d4/d46/diag/pulp_d46.png',

    img_dientepilar: 'assets/images/pages/dientes/d4/d46/diag/dp_d46.png',
    img_protesisp: 'assets/images/pages/dientes/d4/d46/diag/pp.png',
  },
  {
    cod: 'd45',
    nom: '4.5',
    img_sano: 'assets/images/pages/dientes/d4/d45/diag/d45.png',
    img_endodoncia: 'assets/images/pages/dientes/d4/d45/diag/e_d45.png',
    img_endodonciap: 'assets/images/pages/dientes/d4/d45/diag/ep_d45.png',
    img_extraccion: 'assets/images/pages/dientes/d4/d45/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d4/d45/diag/c_d45.png',
    img_implante: 'assets/images/pages/dientes/d4/d45/diag/i_d45.png',
    img_lesion: 'assets/images/pages/dientes/d4/d45/diag/lc_d45.png',
    img_pulpotomia: 'assets/images/pages/dientes/d4/d45/diag/p_d45.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d4/d45/diag/pp_d45.png',
    img_coronaacero: 'assets/images/pages/dientes/d4/d45/diag/cai_d45.png',
    img_coronaacetato: 'assets/images/pages/dientes/d4/d45/diag/ca_d45.png',
    img_fluoruro: 'assets/images/pages/dientes/d4/d45/diag/fp_d45.png',
    img_pulpectomia: 'assets/images/pages/dientes/d4/d45/diag/pul_d45.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d4/d45/diag/pulp_d45.png',

    img_dientepilar: 'assets/images/pages/dientes/d4/d45/diag/dp_d45.png',
    img_protesisp: 'assets/images/pages/dientes/d4/d45/diag/pp.png',
  },
  {
    cod: 'd44',
    nom: '4.4',
    img_sano: 'assets/images/pages/dientes/d4/d44/diag/d44.png',
    img_endodoncia: 'assets/images/pages/dientes/d4/d44/diag/e_d44.png',
    img_endodonciap: 'assets/images/pages/dientes/d4/d44/diag/ep_d44.png',
    img_extraccion: 'assets/images/pages/dientes/d4/d44/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d4/d44/diag/c_d44.png',
    img_implante: 'assets/images/pages/dientes/d4/d44/diag/i_d44.png',
    img_lesion: 'assets/images/pages/dientes/d4/d44/diag/lc_d44.png',
    img_pulpotomia: 'assets/images/pages/dientes/d4/d44/diag/p_d44.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d4/d44/diag/pp_d44.png',
    img_coronaacero: 'assets/images/pages/dientes/d4/d44/diag/cai_d44.png',
    img_coronaacetato: 'assets/images/pages/dientes/d4/d44/diag/ca_d44.png',
    img_fluoruro: 'assets/images/pages/dientes/d4/d44/diag/fp_d44.png',
    img_pulpectomia: 'assets/images/pages/dientes/d4/d44/diag/pul_d44.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d4/d44/diag/pulp_d44.png',

    img_dientepilar: 'assets/images/pages/dientes/d4/d44/diag/dp_d44.png',
    img_protesisp: 'assets/images/pages/dientes/d4/d44/diag/pp.png',
  },
  {
    cod: 'd43',
    nom: '4.3',
    img_sano: 'assets/images/pages/dientes/d4/d43/diag/d43.png',
    img_endodoncia: 'assets/images/pages/dientes/d4/d43/diag/e_d43.png',
    img_endodonciap: 'assets/images/pages/dientes/d4/d43/diag/ep_d43.png',
    img_extraccion: 'assets/images/pages/dientes/d4/d43/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d4/d43/diag/c_d43.png',
    img_implante: 'assets/images/pages/dientes/d4/d43/diag/i_d43.png',
    img_lesion: 'assets/images/pages/dientes/d4/d43/diag/lc_d43.png',
    img_pulpotomia: 'assets/images/pages/dientes/d4/d43/diag/p_d43.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d4/d43/diag/pp_d43.png',
    img_coronaacero: 'assets/images/pages/dientes/d4/d43/diag/cai_d43.png',
    img_coronaacetato: 'assets/images/pages/dientes/d4/d43/diag/ca_d43.png',
    img_fluoruro: 'assets/images/pages/dientes/d4/d43/diag/fp_d43.png',
    img_pulpectomia: 'assets/images/pages/dientes/d4/d43/diag/pul_d43.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d4/d43/diag/pulp_d43.png',

    img_dientepilar: 'assets/images/pages/dientes/d4/d43/diag/dp_d43.png',
    img_protesisp: 'assets/images/pages/dientes/d4/d43/diag/pp.png',
  },
  {
    cod: 'd42',
    nom: '4.2',
    img_sano: 'assets/images/pages/dientes/d4/d42/diag/d42.png',
    img_endodoncia: 'assets/images/pages/dientes/d4/d42/diag/e_d42.png',
    img_endodonciap: 'assets/images/pages/dientes/d4/d42/diag/ep_d42.png',
    img_extraccion: 'assets/images/pages/dientes/d4/d42/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d4/d42/diag/c_d42.png',
    img_implante: 'assets/images/pages/dientes/d4/d42/diag/i_d42.png',
    img_lesion: 'assets/images/pages/dientes/d4/d42/diag/lc_d42.png',
    img_pulpotomia: 'assets/images/pages/dientes/d4/d42/diag/p_d42.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d4/d42/diag/pp_d42.png',
    img_coronaacero: 'assets/images/pages/dientes/d4/d42/diag/cai_d42.png',
    img_coronaacetato: 'assets/images/pages/dientes/d4/d42/diag/ca_d42.png',
    img_fluoruro: 'assets/images/pages/dientes/d4/d42/diag/fp_d42.png',
    img_pulpectomia: 'assets/images/pages/dientes/d4/d42/diag/pul_d42.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d4/d42/diag/pulp_d42.png',

    img_dientepilar: 'assets/images/pages/dientes/d4/d42/diag/dp_d42.png',
    img_protesisp: 'assets/images/pages/dientes/d4/d42/diag/pp.png',
  },
  {
    cod: 'd41',
    nom: '4.1',
    img_sano: 'assets/images/pages/dientes/d4/d41/diag/d41.png',
    img_endodoncia: 'assets/images/pages/dientes/d4/d41/diag/e_d41.png',
    img_endodonciap: 'assets/images/pages/dientes/d4/d41/diag/ep_d41.png',
    img_extraccion: 'assets/images/pages/dientes/d4/d41/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d4/d41/diag/c_d41.png',
    img_implante: 'assets/images/pages/dientes/d4/d41/diag/i_d41.png',
    img_lesion: 'assets/images/pages/dientes/d4/d41/diag/lc_d41.png',
    img_pulpotomia: 'assets/images/pages/dientes/d4/d41/diag/p_d41.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d4/d41/diag/pp_d41.png',
    img_coronaacero: 'assets/images/pages/dientes/d4/d41/diag/cai_d41.png',
    img_coronaacetato: 'assets/images/pages/dientes/d4/d41/diag/ca_d41.png',
    img_fluoruro: 'assets/images/pages/dientes/d4/d41/diag/fp_d41.png',
    img_pulpectomia: 'assets/images/pages/dientes/d4/d41/diag/pul_d41.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d4/d41/diag/pulp_d41.png',

    img_dientepilar: 'assets/images/pages/dientes/d4/d41/diag/dp_d41.png',
    img_protesisp: 'assets/images/pages/dientes/d4/d41/diag/pp.png',
  },
  {
    cod: 'd31',
    nom: '3.1',
    img_sano: 'assets/images/pages/dientes/d3/d31/diag/d31.png',
    img_endodoncia: 'assets/images/pages/dientes/d3/d31/diag/e_d31.png',
    img_endodonciap: 'assets/images/pages/dientes/d3/d31/diag/ep_d31.png',
    img_extraccion: 'assets/images/pages/dientes/d3/d31/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d3/d31/diag/c_d31.png',
    img_implante: 'assets/images/pages/dientes/d3/d31/diag/i_d31.png',
    img_lesion: 'assets/images/pages/dientes/d3/d31/diag/lc_d31.png',
    img_pulpotomia: 'assets/images/pages/dientes/d3/d31/diag/p_d31.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d3/d31/diag/pp_d31.png',
    img_coronaacero: 'assets/images/pages/dientes/d3/d31/diag/cai_d31.png',
    img_coronaacetato: 'assets/images/pages/dientes/d3/d31/diag/ca_d31.png',
    img_fluoruro: 'assets/images/pages/dientes/d3/d31/diag/fp_d31.png',
    img_pulpectomia: 'assets/images/pages/dientes/d3/d31/diag/pul_d31.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d3/d31/diag/pulp_d31.png',

    img_dientepilar: 'assets/images/pages/dientes/d3/d31/diag/dp_d31.png',
    img_protesisp: 'assets/images/pages/dientes/d3/d31/diag/pp.png',
  },
  {
    cod: 'd32',
    nom: '3.2',
    img_sano: 'assets/images/pages/dientes/d3/d32/diag/d32.png',
    img_endodoncia: 'assets/images/pages/dientes/d3/d32/diag/e_d32.png',
    img_endodonciap: 'assets/images/pages/dientes/d3/d32/diag/ep_d32.png',
    img_extraccion: 'assets/images/pages/dientes/d3/d32/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d3/d32/diag/c_d32.png',
    img_implante: 'assets/images/pages/dientes/d3/d32/diag/i_d32.png',
    img_lesion: 'assets/images/pages/dientes/d3/d32/diag/lc_d32.png',
    img_pulpotomia: 'assets/images/pages/dientes/d3/d32/diag/p_d32.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d3/d32/diag/pp_d32.png',
    img_coronaacero: 'assets/images/pages/dientes/d3/d32/diag/cai_d32.png',
    img_coronaacetato: 'assets/images/pages/dientes/d3/d32/diag/ca_d32.png',
    img_fluoruro: 'assets/images/pages/dientes/d3/d32/diag/fp_d32.png',
    img_pulpectomia: 'assets/images/pages/dientes/d3/d32/diag/pul_d32.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d3/d32/diag/pulp_d32.png',

    img_dientepilar: 'assets/images/pages/dientes/d3/d32/diag/dp_d32.png',
    img_protesisp: 'assets/images/pages/dientes/d3/d32/diag/pp.png',
  },
  {
    cod: 'd33',
    nom: '3.3',
    img_sano: 'assets/images/pages/dientes/d3/d33/diag/d33.png',
    img_endodoncia: 'assets/images/pages/dientes/d3/d33/diag/e_d33.png',
    img_endodonciap: 'assets/images/pages/dientes/d3/d33/diag/ep_d33.png',
    img_extraccion: 'assets/images/pages/dientes/d3/d33/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d3/d33/diag/c_d33.png',
    img_implante: 'assets/images/pages/dientes/d3/d33/diag/i_d33.png',
    img_lesion: 'assets/images/pages/dientes/d3/d33/diag/lc_d33.png',
    img_pulpotomia: 'assets/images/pages/dientes/d3/d33/diag/p_d33.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d3/d33/diag/pp_d33.png',
    img_coronaacero: 'assets/images/pages/dientes/d3/d33/diag/cai_d33.png',
    img_coronaacetato: 'assets/images/pages/dientes/d3/d33/diag/ca_d33.png',
    img_fluoruro: 'assets/images/pages/dientes/d3/d33/diag/fp_d33.png',
    img_pulpectomia: 'assets/images/pages/dientes/d3/d33/diag/pul_d33.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d3/d33/diag/pulp_d33.png',

    img_dientepilar: 'assets/images/pages/dientes/d3/d33/diag/dp_d33.png',
    img_protesisp: 'assets/images/pages/dientes/d3/d33/diag/pp.png',
  },
  {
    cod: 'd34',
    nom: '3.4',
    img_sano: 'assets/images/pages/dientes/d3/d34/diag/d34.png',
    img_endodoncia: 'assets/images/pages/dientes/d3/d34/diag/e_d34.png',
    img_endodonciap: 'assets/images/pages/dientes/d3/d34/diag/ep_d34.png',
    img_extraccion: 'assets/images/pages/dientes/d3/d34/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d3/d34/diag/c_d34.png',
    img_implante: 'assets/images/pages/dientes/d3/d34/diag/i_d34.png',
    img_lesion: 'assets/images/pages/dientes/d3/d34/diag/lc_d34.png',
    img_pulpotomia: 'assets/images/pages/dientes/d3/d34/diag/p_d34.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d3/d34/diag/pp_d34.png',
    img_coronaacero: 'assets/images/pages/dientes/d3/d34/diag/cai_d34.png',
    img_coronaacetato: 'assets/images/pages/dientes/d3/d34/diag/ca_d34.png',
    img_fluoruro: 'assets/images/pages/dientes/d3/d34/diag/fp_d34.png',
    img_pulpectomia: 'assets/images/pages/dientes/d3/d34/diag/pul_d34.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d3/d34/diag/pulp_d34.png',

    img_dientepilar: 'assets/images/pages/dientes/d3/d34/diag/dp_d34.png',
    img_protesisp: 'assets/images/pages/dientes/d3/d34/diag/pp.png',
  },
  {
    cod: 'd35',
    nom: '3.5',
    img_sano: 'assets/images/pages/dientes/d3/d35/diag/d35.png',
    img_endodoncia: 'assets/images/pages/dientes/d3/d35/diag/e_d35.png',
    img_endodonciap: 'assets/images/pages/dientes/d3/d35/diag/ep_d35.png',
    img_extraccion: 'assets/images/pages/dientes/d3/d35/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d3/d35/diag/c_d35.png',
    img_implante: 'assets/images/pages/dientes/d3/d35/diag/i_d35.png',
    img_lesion: 'assets/images/pages/dientes/d3/d35/diag/lc_d35.png',
    img_pulpotomia: 'assets/images/pages/dientes/d3/d35/diag/p_d35.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d3/d35/diag/pp_d35.png',
    img_coronaacero: 'assets/images/pages/dientes/d3/d35/diag/cai_d35.png',
    img_coronaacetato: 'assets/images/pages/dientes/d3/d35/diag/ca_d35.png',
    img_fluoruro: 'assets/images/pages/dientes/d3/d35/diag/fp_d35.png',
    img_pulpectomia: 'assets/images/pages/dientes/d3/d35/diag/pul_d35.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d3/d35/diag/pulp_d35.png',

    img_dientepilar: 'assets/images/pages/dientes/d3/d35/diag/dp_d35.png',
    img_protesisp: 'assets/images/pages/dientes/d3/d35/diag/pp.png',
  },
  {
    cod: 'd36',
    nom: '3.6',
    img_sano: 'assets/images/pages/dientes/d3/d36/diag/d36.png',
    img_endodoncia: 'assets/images/pages/dientes/d3/d36/diag/e_d36.png',
    img_endodonciap: 'assets/images/pages/dientes/d3/d36/diag/ep_d36.png',
    img_extraccion: 'assets/images/pages/dientes/d3/d36/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d3/d36/diag/c_d36.png',
    img_implante: 'assets/images/pages/dientes/d3/d36/diag/i_d36.png',
    img_lesion: 'assets/images/pages/dientes/d3/d36/diag/lc_d36.png',
    img_pulpotomia: 'assets/images/pages/dientes/d3/d36/diag/p_d36.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d3/d36/diag/pp_d36.png',
    img_coronaacero: 'assets/images/pages/dientes/d3/d36/diag/cai_d36.png',
    img_coronaacetato: 'assets/images/pages/dientes/d3/d36/diag/ca_d36.png',
    img_fluoruro: 'assets/images/pages/dientes/d3/d36/diag/fp_d36.png',
    img_pulpectomia: 'assets/images/pages/dientes/d3/d36/diag/pul_d36.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d3/d36/diag/pulp_d36.png',

    img_dientepilar: 'assets/images/pages/dientes/d3/d36/diag/dp_d36.png',
    img_protesisp: 'assets/images/pages/dientes/d3/d36/diag/pp.png',
  },
  {
    cod: 'd37',
    nom: '3.7',
    img_sano: 'assets/images/pages/dientes/d3/d37/diag/d37.png',
    img_endodoncia: 'assets/images/pages/dientes/d3/d37/diag/e_d37.png',
    img_endodonciap: 'assets/images/pages/dientes/d3/d37/diag/ep_d37.png',
    img_extraccion: 'assets/images/pages/dientes/d3/d37/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d3/d37/diag/c_d37.png',
    img_implante: 'assets/images/pages/dientes/d3/d37/diag/i_d37.png',
    img_lesion: 'assets/images/pages/dientes/d3/d37/diag/lc_d37.png',
    img_pulpotomia: 'assets/images/pages/dientes/d3/d37/diag/p_d37.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d3/d37/diag/pp_d37.png',
    img_coronaacero: 'assets/images/pages/dientes/d3/d37/diag/cai_d37.png',
    img_coronaacetato: 'assets/images/pages/dientes/d3/d37/diag/ca_d37.png',
    img_fluoruro: 'assets/images/pages/dientes/d3/d37/diag/fp_d37.png',
    img_pulpectomia: 'assets/images/pages/dientes/d3/d37/diag/pul_d37.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d3/d37/diag/pulp_d37.png',

    img_dientepilar: 'assets/images/pages/dientes/d3/d37/diag/dp_d37.png',
    img_protesisp: 'assets/images/pages/dientes/d3/d37/diag/pp.png',
  },
  {
    cod: 'd38',
    nom: '3.8',
    img_sano: 'assets/images/pages/dientes/d3/d38/diag/d38.png',
    img_endodoncia: 'assets/images/pages/dientes/d3/d38/diag/e_d38.png',
    img_endodonciap: 'assets/images/pages/dientes/d3/d38/diag/ep_d38.png',
    img_extraccion: 'assets/images/pages/dientes/d3/d38/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d3/d38/diag/c_d38.png',
    img_implante: 'assets/images/pages/dientes/d3/d38/diag/i_d38.png',
    img_lesion: 'assets/images/pages/dientes/d3/d38/diag/lc_d38.png',
    img_pulpotomia: 'assets/images/pages/dientes/d3/d38/diag/p_d38.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d3/d38/diag/pp_d38.png',
    img_coronaacero: 'assets/images/pages/dientes/d3/d38/diag/cai_d38.png',
    img_coronaacetato: 'assets/images/pages/dientes/d3/d38/diag/ca_d38.png',
    img_fluoruro: 'assets/images/pages/dientes/d3/d38/diag/fp_d38.png',
    img_pulpectomia: 'assets/images/pages/dientes/d3/d38/diag/pul_d38.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d3/d38/diag/pulp_d38.png',

    img_dientepilar: 'assets/images/pages/dientes/d3/d38/diag/dp_d38.png',
    img_protesisp: 'assets/images/pages/dientes/d3/d38/diag/pp.png',
  },
]