
export const INFERIORMENOR = [
  {
    cod: 'd85',
    nom: '8.5',
    img_sano: 'assets/images/pages/dientes/d8/d85/diag/d85.png',
    img_endodoncia: 'assets/images/pages/dientes/d8/d85/diag/e_d85.png',
    img_endodonciap: 'assets/images/pages/dientes/d8/d85/diag/ep_d85.png',
    img_extraccion: 'assets/images/pages/dientes/d8/d85/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d8/d85/diag/c_d85.png',
    img_implante: 'assets/images/pages/dientes/d8/d85/diag/i_d85.png',
    img_lesion: 'assets/images/pages/dientes/d8/d85/diag/lc_d85.png',
    img_pulpotomia: 'assets/images/pages/dientes/d8/d85/diag/p_d85.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d8/d85/diag/pp_d85.png',
    img_coronaacero: 'assets/images/pages/dientes/d8/d85/diag/cai_d85.png',
    img_coronaacetato: 'assets/images/pages/dientes/d8/d85/diag/ca_d85.png',
    img_fluoruro: 'assets/images/pages/dientes/d8/d85/diag/fp_d85.png',
    img_pulpectomia: 'assets/images/pages/dientes/d8/d85/diag/pul_d85.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d8/d85/diag/pulp_d85.png',

    img_dientepilar: 'assets/images/pages/dientes/d8/d85/diag/dp_d85.png',
    img_protesisp: 'assets/images/pages/dientes/d8/d85/diag/pp.png',
  },
  {
    cod: 'd84',
    nom: '8.4',
    img_sano: 'assets/images/pages/dientes/d8/d84/diag/d84.png',
    img_endodoncia: 'assets/images/pages/dientes/d8/d84/diag/e_d84.png',
    img_endodonciap: 'assets/images/pages/dientes/d8/d84/diag/ep_d84.png',
    img_extraccion: 'assets/images/pages/dientes/d8/d84/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d8/d84/diag/c_d84.png',
    img_implante: 'assets/images/pages/dientes/d8/d84/diag/i_d84.png',
    img_lesion: 'assets/images/pages/dientes/d8/d84/diag/lc_d84.png',
    img_pulpotomia: 'assets/images/pages/dientes/d8/d84/diag/p_d84.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d8/d84/diag/pp_d84.png',
    img_coronaacero: 'assets/images/pages/dientes/d8/d84/diag/cai_d84.png',
    img_coronaacetato: 'assets/images/pages/dientes/d8/d84/diag/ca_d84.png',
    img_fluoruro: 'assets/images/pages/dientes/d8/d84/diag/fp_d84.png',
    img_pulpectomia: 'assets/images/pages/dientes/d8/d84/diag/pul_d84.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d8/d84/diag/pulp_d84.png',

    img_dientepilar: 'assets/images/pages/dientes/d8/d84/diag/dp_d84.png',
    img_protesisp: 'assets/images/pages/dientes/d8/d84/diag/pp.png',
  },
  {
    cod: 'd83',
    nom: '8.3',
    img_sano: 'assets/images/pages/dientes/d8/d83/diag/d83.png',
    img_endodoncia: 'assets/images/pages/dientes/d8/d83/diag/e_d83.png',
    img_endodonciap: 'assets/images/pages/dientes/d8/d83/diag/ep_d83.png',
    img_extraccion: 'assets/images/pages/dientes/d8/d83/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d8/d83/diag/c_d83.png',
    img_implante: 'assets/images/pages/dientes/d8/d83/diag/i_d83.png',
    img_lesion: 'assets/images/pages/dientes/d8/d83/diag/lc_d83.png',
    img_pulpotomia: 'assets/images/pages/dientes/d8/d83/diag/p_d83.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d8/d83/diag/pp_d83.png',
    img_coronaacero: 'assets/images/pages/dientes/d8/d83/diag/cai_d83.png',
    img_coronaacetato: 'assets/images/pages/dientes/d8/d83/diag/ca_d83.png',
    img_fluoruro: 'assets/images/pages/dientes/d8/d83/diag/fp_d83.png',
    img_pulpectomia: 'assets/images/pages/dientes/d8/d83/diag/pul_d83.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d8/d83/diag/pulp_d83.png',

    img_dientepilar: 'assets/images/pages/dientes/d8/d83/diag/dp_d83.png',
    img_protesisp: 'assets/images/pages/dientes/d8/d83/diag/pp.png',
  },
  {
    cod: 'd82',
    nom: '8.2',
    img_sano: 'assets/images/pages/dientes/d8/d82/diag/d82.png',
    img_endodoncia: 'assets/images/pages/dientes/d8/d82/diag/e_d82.png',
    img_endodonciap: 'assets/images/pages/dientes/d8/d82/diag/ep_d82.png',
    img_extraccion: 'assets/images/pages/dientes/d8/d82/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d8/d82/diag/c_d82.png',
    img_implante: 'assets/images/pages/dientes/d8/d82/diag/i_d82.png',
    img_lesion: 'assets/images/pages/dientes/d8/d82/diag/lc_d82.png',
    img_pulpotomia: 'assets/images/pages/dientes/d8/d82/diag/p_d82.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d8/d82/diag/pp_d82.png',
    img_coronaacero: 'assets/images/pages/dientes/d8/d82/diag/cai_d82.png',
    img_coronaacetato: 'assets/images/pages/dientes/d8/d82/diag/ca_d82.png',
    img_fluoruro: 'assets/images/pages/dientes/d8/d82/diag/fp_d82.png',
    img_pulpectomia: 'assets/images/pages/dientes/d8/d82/diag/pul_d82.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d8/d82/diag/pulp_d82.png',

    img_dientepilar: 'assets/images/pages/dientes/d8/d82/diag/dp_d82.png',
    img_protesisp: 'assets/images/pages/dientes/d8/d82/diag/pp.png',
  },
  {
    cod: 'd81',
    nom: '8.1',
    img_sano: 'assets/images/pages/dientes/d8/d81/diag/d81.png',
    img_endodoncia: 'assets/images/pages/dientes/d8/d81/diag/e_d81.png',
    img_endodonciap: 'assets/images/pages/dientes/d8/d81/diag/ep_d81.png',
    img_extraccion: 'assets/images/pages/dientes/d8/d81/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d8/d81/diag/c_d81.png',
    img_implante: 'assets/images/pages/dientes/d8/d81/diag/i_d81.png',
    img_lesion: 'assets/images/pages/dientes/d8/d81/diag/lc_d81.png',
    img_pulpotomia: 'assets/images/pages/dientes/d8/d81/diag/p_d81.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d8/d81/diag/pp_d81.png',
    img_coronaacero: 'assets/images/pages/dientes/d8/d81/diag/cai_d81.png',
    img_coronaacetato: 'assets/images/pages/dientes/d8/d81/diag/ca_d81.png',
    img_fluoruro: 'assets/images/pages/dientes/d8/d81/diag/fp_d81.png',
    img_pulpectomia: 'assets/images/pages/dientes/d8/d81/diag/pul_d81.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d8/d81/diag/pulp_d81.png',

    img_dientepilar: 'assets/images/pages/dientes/d8/d81/diag/dp_d81.png',
    img_protesisp: 'assets/images/pages/dientes/d8/d81/diag/pp.png',
  },
  {
    cod: 'd71',
    nom: '7.1',
    img_sano: 'assets/images/pages/dientes/d7/d71/diag/d71.png',
    img_endodoncia: 'assets/images/pages/dientes/d7/d71/diag/e_d71.png',
    img_endodonciap: 'assets/images/pages/dientes/d7/d71/diag/ep_d71.png',
    img_extraccion: 'assets/images/pages/dientes/d7/d71/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d7/d71/diag/c_d71.png',
    img_implante: 'assets/images/pages/dientes/d7/d71/diag/i_d71.png',
    img_lesion: 'assets/images/pages/dientes/d7/d71/diag/lc_d71.png',
    img_pulpotomia: 'assets/images/pages/dientes/d7/d71/diag/p_d71.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d7/d71/diag/pp_d71.png',
    img_coronaacero: 'assets/images/pages/dientes/d7/d71/diag/cai_d71.png',
    img_coronaacetato: 'assets/images/pages/dientes/d7/d71/diag/ca_d71.png',
    img_fluoruro: 'assets/images/pages/dientes/d7/d71/diag/fp_d71.png',
    img_pulpectomia: 'assets/images/pages/dientes/d7/d71/diag/pul_d71.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d7/d71/diag/pulp_d71.png',

    img_dientepilar: 'assets/images/pages/dientes/d7/d71/diag/dp_d71.png',
    img_protesisp: 'assets/images/pages/dientes/d7/d71/diag/pp.png',
  },
  {
    cod: 'd72',
    nom: '7.2',
    img_sano: 'assets/images/pages/dientes/d7/d72/diag/d72.png',
    img_endodoncia: 'assets/images/pages/dientes/d7/d72/diag/e_d72.png',
    img_endodonciap: 'assets/images/pages/dientes/d7/d72/diag/ep_d72.png',
    img_extraccion: 'assets/images/pages/dientes/d7/d72/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d7/d72/diag/c_d72.png',
    img_implante: 'assets/images/pages/dientes/d7/d72/diag/i_d72.png',
    img_lesion: 'assets/images/pages/dientes/d7/d72/diag/lc_d72.png',
    img_pulpotomia: 'assets/images/pages/dientes/d7/d72/diag/p_d72.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d7/d72/diag/pp_d72.png',
    img_coronaacero: 'assets/images/pages/dientes/d7/d72/diag/cai_d72.png',
    img_coronaacetato: 'assets/images/pages/dientes/d7/d72/diag/ca_d72.png',
    img_fluoruro: 'assets/images/pages/dientes/d7/d72/diag/fp_d72.png',
    img_pulpectomia: 'assets/images/pages/dientes/d7/d72/diag/pul_d72.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d7/d72/diag/pulp_d72.png',

    img_dientepilar: 'assets/images/pages/dientes/d7/d72/diag/dp_d72.png',
    img_protesisp: 'assets/images/pages/dientes/d7/d72/diag/pp.png',
  },
  {
    cod: 'd73',
    nom: '7.3',
    img_sano: 'assets/images/pages/dientes/d7/d73/diag/d73.png',
    img_endodoncia: 'assets/images/pages/dientes/d7/d73/diag/e_d73.png',
    img_endodonciap: 'assets/images/pages/dientes/d7/d73/diag/ep_d73.png',
    img_extraccion: 'assets/images/pages/dientes/d7/d73/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d7/d73/diag/c_d73.png',
    img_implante: 'assets/images/pages/dientes/d7/d73/diag/i_d73.png',
    img_lesion: 'assets/images/pages/dientes/d7/d73/diag/lc_d73.png',
    img_pulpotomia: 'assets/images/pages/dientes/d7/d73/diag/p_d73.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d7/d73/diag/pp_d73.png',
    img_coronaacero: 'assets/images/pages/dientes/d7/d73/diag/cai_d73.png',
    img_coronaacetato: 'assets/images/pages/dientes/d7/d73/diag/ca_d73.png',
    img_fluoruro: 'assets/images/pages/dientes/d7/d73/diag/fp_d73.png',
    img_pulpectomia: 'assets/images/pages/dientes/d7/d73/diag/pul_d73.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d7/d73/diag/pulp_d73.png',

    img_dientepilar: 'assets/images/pages/dientes/d7/d73/diag/dp_d73.png',
    img_protesisp: 'assets/images/pages/dientes/d7/d73/diag/pp.png',
  },
  {
    cod: 'd74',
    nom: '7.4',
    img_sano: 'assets/images/pages/dientes/d7/d74/diag/d74.png',
    img_endodoncia: 'assets/images/pages/dientes/d7/d74/diag/e_d74.png',
    img_endodonciap: 'assets/images/pages/dientes/d7/d74/diag/ep_d74.png',
    img_extraccion: 'assets/images/pages/dientes/d7/d74/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d7/d74/diag/c_d74.png',
    img_implante: 'assets/images/pages/dientes/d7/d74/diag/i_d74.png',
    img_lesion: 'assets/images/pages/dientes/d7/d74/diag/lc_d74.png',
    img_pulpotomia: 'assets/images/pages/dientes/d7/d74/diag/p_d74.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d7/d74/diag/pp_d74.png',
    img_coronaacero: 'assets/images/pages/dientes/d7/d74/diag/cai_d74.png',
    img_coronaacetato: 'assets/images/pages/dientes/d7/d74/diag/ca_d74.png',
    img_fluoruro: 'assets/images/pages/dientes/d7/d74/diag/fp_d74.png',
    img_pulpectomia: 'assets/images/pages/dientes/d7/d74/diag/pul_d74.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d7/d74/diag/pulp_d74.png',

    img_dientepilar: 'assets/images/pages/dientes/d7/d74/diag/dp_d74.png',
    img_protesisp: 'assets/images/pages/dientes/d7/d74/diag/pp.png',
  },
  {
    cod: 'd75',
    nom: '7.5',
    img_sano: 'assets/images/pages/dientes/d7/d75/diag/d75.png',
    img_endodoncia: 'assets/images/pages/dientes/d7/d75/diag/e_d75.png',
    img_endodonciap: 'assets/images/pages/dientes/d7/d75/diag/ep_d75.png',
    img_extraccion: 'assets/images/pages/dientes/d7/d75/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d7/d75/diag/c_d75.png',
    img_implante: 'assets/images/pages/dientes/d7/d75/diag/i_d75.png',
    img_lesion: 'assets/images/pages/dientes/d7/d75/diag/lc_d75.png',
    img_pulpotomia: 'assets/images/pages/dientes/d7/d75/diag/p_d75.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d7/d75/diag/pp_d75.png',
    img_coronaacero: 'assets/images/pages/dientes/d7/d75/diag/cai_d75.png',
    img_coronaacetato: 'assets/images/pages/dientes/d7/d75/diag/ca_d75.png',
    img_fluoruro: 'assets/images/pages/dientes/d7/d75/diag/fp_d75.png',
    img_pulpectomia: 'assets/images/pages/dientes/d7/d75/diag/pul_d75.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d7/d75/diag/pulp_d75.png',

    img_dientepilar: 'assets/images/pages/dientes/d7/d75/diag/dp_d75.png',
    img_protesisp: 'assets/images/pages/dientes/d7/d75/diag/pp.png',
  },
]