
export const SUPERIORADULTO = [
  {
    cod: 'd18',
    nom: '1.8',
    img_sano: 'assets/images/pages/dientes/d1/d18/diag/d18.png',
    img_endodoncia: 'assets/images/pages/dientes/d1/d18/diag/e_d18.png',
    img_endodonciap: 'assets/images/pages/dientes/d1/d18/diag/ep_d18.png',
    img_extraccion: 'assets/images/pages/dientes/d1/d18/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d1/d18/diag/c_d18.png',
    img_implante: 'assets/images/pages/dientes/d1/d18/diag/i_d18.png',
    img_lesion: 'assets/images/pages/dientes/d1/d18/diag/lc_d18.png',
    img_pulpotomia: 'assets/images/pages/dientes/d1/d18/diag/p_d18.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d1/d18/diag/pp_d18.png',
    img_coronaacero: 'assets/images/pages/dientes/d1/d18/diag/cai_d18.png',
    img_coronaacetato: 'assets/images/pages/dientes/d1/d18/diag/ca_d18.png',
    img_fluoruro: 'assets/images/pages/dientes/d1/d18/diag/fp_d18.png',
    img_pulpectomia: 'assets/images/pages/dientes/d1/d18/diag/pul_d18.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d1/d18/diag/pulp_d18.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d1/d18/diag/dp_d18.png',
    img_protesisp: 'assets/images/pages/dientes/d1/d18/diag/pp.png',
  },
  {
    cod: 'd17',
    nom: '1.7',
    img_sano: 'assets/images/pages/dientes/d1/d17/diag/d17.png',
    img_endodoncia: 'assets/images/pages/dientes/d1/d17/diag/e_d17.png',
    img_endodonciap: 'assets/images/pages/dientes/d1/d17/diag/ep_d17.png',
    img_extraccion: 'assets/images/pages/dientes/d1/d17/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d1/d17/diag/c_d17.png',
    img_implante: 'assets/images/pages/dientes/d1/d17/diag/i_d17.png',
    img_lesion: 'assets/images/pages/dientes/d1/d17/diag/lc_d17.png',
    img_pulpotomia: 'assets/images/pages/dientes/d1/d17/diag/p_d17.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d1/d17/diag/pp_d17.png',
    img_coronaacero: 'assets/images/pages/dientes/d1/d17/diag/cai_d17.png',
    img_coronaacetato: 'assets/images/pages/dientes/d1/d17/diag/ca_d17.png',
    img_fluoruro: 'assets/images/pages/dientes/d1/d17/diag/fp_d17.png',
    img_pulpectomia: 'assets/images/pages/dientes/d1/d17/diag/pul_d17.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d1/d17/diag/pulp_d17.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d1/d17/diag/dp_d17.png',
    img_protesisp: 'assets/images/pages/dientes/d1/d17/diag/pp.png',
  },
  {
    cod: 'd16',
    nom: '1.6',
    img_sano: 'assets/images/pages/dientes/d1/d16/diag/d16.png',
    img_endodoncia: 'assets/images/pages/dientes/d1/d16/diag/e_d16.png',
    img_endodonciap: 'assets/images/pages/dientes/d1/d16/diag/ep_d16.png',
    img_extraccion: 'assets/images/pages/dientes/d1/d16/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d1/d16/diag/c_d16.png',
    img_implante: 'assets/images/pages/dientes/d1/d16/diag/i_d16.png',
    img_lesion: 'assets/images/pages/dientes/d1/d16/diag/lc_d16.png',
    img_pulpotomia: 'assets/images/pages/dientes/d1/d16/diag/p_d16.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d1/d16/diag/pp_d16.png',
    img_coronaacero: 'assets/images/pages/dientes/d1/d16/diag/cai_d16.png',
    img_coronaacetato: 'assets/images/pages/dientes/d1/d16/diag/ca_d16.png',
    img_fluoruro: 'assets/images/pages/dientes/d1/d16/diag/fp_d16.png',
    img_pulpectomia: 'assets/images/pages/dientes/d1/d16/diag/pul_d16.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d1/d16/diag/pulp_d16.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d1/d16/diag/dp_d16.png',
    img_protesisp: 'assets/images/pages/dientes/d1/d16/diag/pp.png',
  },
  {
    cod: 'd15',
    nom: '1.5',
    img_sano: 'assets/images/pages/dientes/d1/d15/diag/d15.png',
    img_endodoncia: 'assets/images/pages/dientes/d1/d15/diag/e_d15.png',
    img_endodonciap: 'assets/images/pages/dientes/d1/d15/diag/ep_d15.png',
    img_extraccion: 'assets/images/pages/dientes/d1/d15/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d1/d15/diag/c_d15.png',
    img_implante: 'assets/images/pages/dientes/d1/d15/diag/i_d15.png',
    img_lesion: 'assets/images/pages/dientes/d1/d15/diag/lc_d15.png',
    img_pulpotomia: 'assets/images/pages/dientes/d1/d15/diag/p_d15.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d1/d15/diag/pp_d15.png',
    img_coronaacero: 'assets/images/pages/dientes/d1/d15/diag/cai_d15.png',
    img_coronaacetato: 'assets/images/pages/dientes/d1/d15/diag/ca_d15.png',
    img_fluoruro: 'assets/images/pages/dientes/d1/d15/diag/fp_d15.png',
    img_pulpectomia: 'assets/images/pages/dientes/d1/d15/diag/pul_d15.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d1/d15/diag/pulp_d15.png',

    img_dientepilar: 'assets/images/pages/dientes/d1/d15/diag/dp_d15.png',
    img_protesisp: 'assets/images/pages/dientes/d1/d15/diag/pp.png',
  },
  {
    cod: 'd14',
    nom: '1.4',
    img_sano: 'assets/images/pages/dientes/d1/d14/diag/d14.png',
    img_endodoncia: 'assets/images/pages/dientes/d1/d14/diag/e_d14.png',
    img_endodonciap: 'assets/images/pages/dientes/d1/d14/diag/ep_d14.png',
    img_extraccion: 'assets/images/pages/dientes/d1/d14/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d1/d14/diag/c_d14.png',
    img_implante: 'assets/images/pages/dientes/d1/d14/diag/i_d14.png',
    img_lesion: 'assets/images/pages/dientes/d1/d14/diag/lc_d14.png',
    img_pulpotomia: 'assets/images/pages/dientes/d1/d14/diag/p_d14.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d1/d14/diag/pp_d14.png',
    img_coronaacero: 'assets/images/pages/dientes/d1/d14/diag/cai_d14.png',
    img_coronaacetato: 'assets/images/pages/dientes/d1/d14/diag/ca_d14.png',
    img_fluoruro: 'assets/images/pages/dientes/d1/d14/diag/fp_d14.png',
    img_pulpectomia: 'assets/images/pages/dientes/d1/d14/diag/pul_d14.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d1/d14/diag/pulp_d14.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d1/d14/diag/dp_d14.png',
    img_protesisp: 'assets/images/pages/dientes/d1/d14/diag/pp.png',
  },
  {
    cod: 'd13',
    nom: '1.3',
    img_sano: 'assets/images/pages/dientes/d1/d13/diag/d13.png',
    img_endodoncia: 'assets/images/pages/dientes/d1/d13/diag/e_d13.png',
    img_endodonciap: 'assets/images/pages/dientes/d1/d13/diag/ep_d13.png',
    img_extraccion: 'assets/images/pages/dientes/d1/d13/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d1/d13/diag/c_d13.png',
    img_implante: 'assets/images/pages/dientes/d1/d13/diag/i_d13.png',
    img_lesion: 'assets/images/pages/dientes/d1/d13/diag/lc_d13.png',
    img_pulpotomia: 'assets/images/pages/dientes/d1/d13/diag/p_d13.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d1/d13/diag/pp_d13.png',
    img_coronaacero: 'assets/images/pages/dientes/d1/d13/diag/cai_d13.png',
    img_coronaacetato: 'assets/images/pages/dientes/d1/d13/diag/ca_d13.png',
    img_fluoruro: 'assets/images/pages/dientes/d1/d13/diag/fp_d13.png',
    img_pulpectomia: 'assets/images/pages/dientes/d1/d13/diag/pul_d13.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d1/d13/diag/pulp_d13.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d1/d13/diag/dp_d13.png',
    img_protesisp: 'assets/images/pages/dientes/d1/d13/diag/pp.png',
  },
  {
    cod: 'd12',
    nom: '1.2',
    img_sano: 'assets/images/pages/dientes/d1/d12/diag/d12.png',
    img_endodoncia: 'assets/images/pages/dientes/d1/d12/diag/e_d12.png',
    img_endodonciap: 'assets/images/pages/dientes/d1/d12/diag/ep_d12.png',
    img_extraccion: 'assets/images/pages/dientes/d1/d12/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d1/d12/diag/c_d12.png',
    img_implante: 'assets/images/pages/dientes/d1/d12/diag/i_d12.png',
    img_lesion: 'assets/images/pages/dientes/d1/d12/diag/lc_d12.png',
    img_pulpotomia: 'assets/images/pages/dientes/d1/d12/diag/p_d12.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d1/d12/diag/pp_d12.png',
    img_coronaacero: 'assets/images/pages/dientes/d1/d12/diag/cai_d12.png',
    img_coronaacetato: 'assets/images/pages/dientes/d1/d12/diag/ca_d12.png',
    img_fluoruro: 'assets/images/pages/dientes/d1/d12/diag/fp_d12.png',
    img_pulpectomia: 'assets/images/pages/dientes/d1/d12/diag/pul_d12.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d1/d12/diag/pulp_d12.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d1/d12/diag/dp_d12.png',
    img_protesisp: 'assets/images/pages/dientes/d1/d12/diag/pp.png',
  },
  {
    cod: 'd11',
    nom: '1.1',
    img_sano: 'assets/images/pages/dientes/d1/d11/diag/d11.png',
    img_endodoncia: 'assets/images/pages/dientes/d1/d11/diag/e_d11.png',
    img_endodonciap: 'assets/images/pages/dientes/d1/d11/diag/ep_d11.png',
    img_extraccion: 'assets/images/pages/dientes/d1/d11/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d1/d11/diag/c_d11.png',
    img_implante: 'assets/images/pages/dientes/d1/d11/diag/i_d11.png',
    img_lesion: 'assets/images/pages/dientes/d1/d11/diag/lc_d11.png',
    img_pulpotomia: 'assets/images/pages/dientes/d1/d11/diag/p_d11.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d1/d11/diag/pp_d11.png',
    img_coronaacero: 'assets/images/pages/dientes/d1/d11/diag/cai_d11.png',
    img_coronaacetato: 'assets/images/pages/dientes/d1/d11/diag/ca_d11.png',
    img_fluoruro: 'assets/images/pages/dientes/d1/d11/diag/fp_d11.png',
    img_pulpectomia: 'assets/images/pages/dientes/d1/d11/diag/pul_d11.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d1/d11/diag/pulp_d11.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d1/d11/diag/dp_d11.png',
    img_protesisp: 'assets/images/pages/dientes/d1/d11/diag/pp.png',
  },
  {
    cod: 'd21',
    nom: '2.1',
    img_sano: 'assets/images/pages/dientes/d2/d21/diag/d21.png',
    img_endodoncia: 'assets/images/pages/dientes/d2/d21/diag/e_d21.png',
    img_endodonciap: 'assets/images/pages/dientes/d2/d21/diag/ep_d21.png',
    img_extraccion: 'assets/images/pages/dientes/d2/d21/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d2/d21/diag/c_d21.png',
    img_implante: 'assets/images/pages/dientes/d2/d21/diag/i_d21.png',
    img_lesion: 'assets/images/pages/dientes/d2/d21/diag/lc_d21.png',
    img_pulpotomia: 'assets/images/pages/dientes/d2/d21/diag/p_d21.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d2/d21/diag/pp_d21.png',
    img_coronaacero: 'assets/images/pages/dientes/d2/d21/diag/cai_d21.png',
    img_coronaacetato: 'assets/images/pages/dientes/d2/d21/diag/ca_d21.png',
    img_fluoruro: 'assets/images/pages/dientes/d2/d21/diag/fp_d21.png',
    img_pulpectomia: 'assets/images/pages/dientes/d2/d21/diag/pul_d21.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d2/d21/diag/pulp_d21.png',

    img_dientepilar: 'assets/images/pages/dientes/d2/d21/diag/dp_d21.png',
    img_protesisp: 'assets/images/pages/dientes/d2/d21/diag/pp.png',
  },
  {
    cod: 'd22',
    nom: '2.2',
    img_sano: 'assets/images/pages/dientes/d2/d22/diag/d22.png',
    img_endodoncia: 'assets/images/pages/dientes/d2/d22/diag/e_d22.png',
    img_endodonciap: 'assets/images/pages/dientes/d2/d22/diag/ep_d22.png',
    img_extraccion: 'assets/images/pages/dientes/d2/d22/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d2/d22/diag/c_d22.png',
    img_implante: 'assets/images/pages/dientes/d2/d22/diag/i_d22.png',
    img_lesion: 'assets/images/pages/dientes/d2/d22/diag/lc_d22.png',
    img_pulpotomia: 'assets/images/pages/dientes/d2/d22/diag/p_d22.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d2/d22/diag/pp_d22.png',
    img_coronaacero: 'assets/images/pages/dientes/d2/d22/diag/cai_d22.png',
    img_coronaacetato: 'assets/images/pages/dientes/d2/d22/diag/ca_d22.png',
    img_fluoruro: 'assets/images/pages/dientes/d2/d22/diag/fp_d22.png',
    img_pulpectomia: 'assets/images/pages/dientes/d2/d22/diag/pul_d22.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d2/d22/diag/pulp_d22.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d2/d22/diag/dp_d22.png',
    img_protesisp: 'assets/images/pages/dientes/d2/d22/diag/pp.png',
  },
  {
    cod: 'd23',
    nom: '2.3',
    img_sano: 'assets/images/pages/dientes/d2/d23/diag/d23.png',
    img_endodoncia: 'assets/images/pages/dientes/d2/d23/diag/e_d23.png',
    img_endodonciap: 'assets/images/pages/dientes/d2/d23/diag/ep_d23.png',
    img_extraccion: 'assets/images/pages/dientes/d2/d23/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d2/d23/diag/c_d23.png',
    img_implante: 'assets/images/pages/dientes/d2/d23/diag/i_d23.png',
    img_lesion: 'assets/images/pages/dientes/d2/d23/diag/lc_d23.png',
    img_pulpotomia: 'assets/images/pages/dientes/d2/d23/diag/p_d23.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d2/d23/diag/pp_d23.png',
    img_coronaacero: 'assets/images/pages/dientes/d2/d23/diag/cai_d23.png',
    img_coronaacetato: 'assets/images/pages/dientes/d2/d23/diag/ca_d23.png',
    img_fluoruro: 'assets/images/pages/dientes/d2/d23/diag/fp_d23.png',
    img_pulpectomia: 'assets/images/pages/dientes/d2/d23/diag/pul_d23.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d2/d23/diag/pulp_d23.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d2/d23/diag/dp_d23.png',
    img_protesisp: 'assets/images/pages/dientes/d2/d23/diag/pp.png',
  },
  {
    cod: 'd24',
    nom: '2.4',
    img_sano: 'assets/images/pages/dientes/d2/d24/diag/d24.png',
    img_endodoncia: 'assets/images/pages/dientes/d2/d24/diag/e_d24.png',
    img_endodonciap: 'assets/images/pages/dientes/d2/d24/diag/ep_d24.png',
    img_extraccion: 'assets/images/pages/dientes/d2/d24/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d2/d24/diag/c_d24.png',
    img_implante: 'assets/images/pages/dientes/d2/d24/diag/i_d24.png',
    img_lesion: 'assets/images/pages/dientes/d2/d24/diag/lc_d24.png',
    img_pulpotomia: 'assets/images/pages/dientes/d2/d24/diag/p_d24.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d2/d24/diag/pp_d24.png',
    img_coronaacero: 'assets/images/pages/dientes/d2/d24/diag/cai_d24.png',
    img_coronaacetato: 'assets/images/pages/dientes/d2/d24/diag/ca_d24.png',
    img_fluoruro: 'assets/images/pages/dientes/d2/d24/diag/fp_d24.png',
    img_pulpectomia: 'assets/images/pages/dientes/d2/d24/diag/pul_d24.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d2/d24/diag/pulp_d24.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d2/d24/diag/dp_d24.png',
    img_protesisp: 'assets/images/pages/dientes/d2/d24/diag/pp.png',
  },
  {
    cod: 'd25',
    nom: '2.5',
    img_sano: 'assets/images/pages/dientes/d2/d25/diag/d25.png',
    img_endodoncia: 'assets/images/pages/dientes/d2/d25/diag/e_d25.png',
    img_endodonciap: 'assets/images/pages/dientes/d2/d25/diag/ep_d25.png',
    img_extraccion: 'assets/images/pages/dientes/d2/d25/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d2/d25/diag/c_d25.png',
    img_implante: 'assets/images/pages/dientes/d2/d25/diag/i_d25.png',
    img_lesion: 'assets/images/pages/dientes/d2/d25/diag/lc_d25.png',
    img_pulpotomia: 'assets/images/pages/dientes/d2/d25/diag/p_d25.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d2/d25/diag/pp_d25.png',
    img_coronaacero: 'assets/images/pages/dientes/d2/d25/diag/cai_d25.png',
    img_coronaacetato: 'assets/images/pages/dientes/d2/d25/diag/ca_d25.png',
    img_fluoruro: 'assets/images/pages/dientes/d2/d25/diag/fp_d25.png',
    img_pulpectomia: 'assets/images/pages/dientes/d2/d25/diag/pul_d25.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d2/d25/diag/pulp_d25.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d2/d25/diag/dp_d25.png',
    img_protesisp: 'assets/images/pages/dientes/d2/d25/diag/pp.png',
  },
  {
    cod: 'd26',
    nom: '2.6',
    img_sano: 'assets/images/pages/dientes/d2/d26/diag/d26.png',
    img_endodoncia: 'assets/images/pages/dientes/d2/d26/diag/e_d26.png',
    img_endodonciap: 'assets/images/pages/dientes/d2/d26/diag/ep_d26.png',
    img_extraccion: 'assets/images/pages/dientes/d2/d26/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d2/d26/diag/c_d26.png',
    img_implante: 'assets/images/pages/dientes/d2/d26/diag/i_d26.png',
    img_lesion: 'assets/images/pages/dientes/d2/d26/diag/lc_d26.png',
    img_pulpotomia: 'assets/images/pages/dientes/d2/d26/diag/p_d26.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d2/d26/diag/pp_d26.png',
    img_coronaacero: 'assets/images/pages/dientes/d2/d26/diag/cai_d26.png',
    img_coronaacetato: 'assets/images/pages/dientes/d2/d26/diag/ca_d26.png',
    img_fluoruro: 'assets/images/pages/dientes/d2/d26/diag/fp_d26.png',
    img_pulpectomia: 'assets/images/pages/dientes/d2/d26/diag/pul_d26.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d2/d26/diag/pulp_d26.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d2/d26/diag/dp_d26.png',
    img_protesisp: 'assets/images/pages/dientes/d2/d26/diag/pp.png',
  },
  {
    cod: 'd27',
    nom: '2.7',
    img_sano: 'assets/images/pages/dientes/d2/d27/diag/d27.png',
    img_endodoncia: 'assets/images/pages/dientes/d2/d27/diag/e_d27.png',
    img_endodonciap: 'assets/images/pages/dientes/d2/d27/diag/ep_d27.png',
    img_extraccion: 'assets/images/pages/dientes/d2/d27/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d2/d27/diag/c_d27.png',
    img_implante: 'assets/images/pages/dientes/d2/d27/diag/i_d27.png',
    img_lesion: 'assets/images/pages/dientes/d2/d27/diag/lc_d27.png',
    img_pulpotomia: 'assets/images/pages/dientes/d2/d27/diag/p_d27.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d2/d27/diag/pp_d27.png',
    img_coronaacero: 'assets/images/pages/dientes/d2/d27/diag/cai_d27.png',
    img_coronaacetato: 'assets/images/pages/dientes/d2/d27/diag/ca_d27.png',
    img_fluoruro: 'assets/images/pages/dientes/d2/d27/diag/fp_d27.png',
    img_pulpectomia: 'assets/images/pages/dientes/d2/d27/diag/pul_d27.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d2/d27/diag/pulp_d27.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d2/d27/diag/dp_d27.png',
    img_protesisp: 'assets/images/pages/dientes/d2/d27/diag/pp.png',
  },
  {
    cod: 'd28',
    nom: '2.8',
    img_sano: 'assets/images/pages/dientes/d2/d28/diag/d28.png',
    img_endodoncia: 'assets/images/pages/dientes/d2/d28/diag/e_d28.png',
    img_endodonciap: 'assets/images/pages/dientes/d2/d28/diag/ep_d28.png',
    img_extraccion: 'assets/images/pages/dientes/d2/d28/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d2/d28/diag/c_d28.png',
    img_implante: 'assets/images/pages/dientes/d2/d28/diag/i_d28.png',
    img_lesion: 'assets/images/pages/dientes/d2/d28/diag/lc_d28.png',
    img_pulpotomia: 'assets/images/pages/dientes/d2/d28/diag/p_d28.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d2/d28/diag/pp_d28.png',
    img_coronaacero: 'assets/images/pages/dientes/d2/d28/diag/cai_d28.png',
    img_coronaacetato: 'assets/images/pages/dientes/d2/d28/diag/ca_d28.png',
    img_fluoruro: 'assets/images/pages/dientes/d2/d28/diag/fp_d28.png',
    img_pulpectomia: 'assets/images/pages/dientes/d2/d28/diag/pul_d28.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d2/d28/diag/pulp_d28.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d2/d28/diag/dp_d28.png',
    img_protesisp: 'assets/images/pages/dientes/d2/d28/diag/pp.png',
  },
]