
export const SUPERIORMENOR = [
  {
    cod: 'd55',
    nom: '5.5',
    img_sano: 'assets/images/pages/dientes/d5/d55/diag/d55.png',
    img_endodoncia: 'assets/images/pages/dientes/d5/d55/diag/e_d55.png',
    img_endodonciap: 'assets/images/pages/dientes/d5/d55/diag/ep_d55.png',
    img_extraccion: 'assets/images/pages/dientes/d5/d55/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d5/d55/diag/c_d55.png',
    img_implante: 'assets/images/pages/dientes/d5/d55/diag/i_d55.png',
    img_lesion: 'assets/images/pages/dientes/d5/d55/diag/lc_d55.png',
    img_pulpotomia: 'assets/images/pages/dientes/d5/d55/diag/p_d55.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d5/d55/diag/pp_d55.png',
    img_coronaacero: 'assets/images/pages/dientes/d5/d55/diag/cai_d55.png',
    img_coronaacetato: 'assets/images/pages/dientes/d5/d55/diag/ca_d55.png',
    img_fluoruro: 'assets/images/pages/dientes/d5/d55/diag/fp_d55.png',
    img_pulpectomia: 'assets/images/pages/dientes/d5/d55/diag/pul_d55.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d5/d55/diag/pulp_d55.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d5/d55/diag/dp_d55.png',
    img_protesisp: 'assets/images/pages/dientes/d5/d55/diag/pp.png',
  },
  {
    cod: 'd54',
    nom: '5.4',
    img_sano: 'assets/images/pages/dientes/d5/d54/diag/d54.png',
    img_endodoncia: 'assets/images/pages/dientes/d5/d54/diag/e_d54.png',
    img_endodonciap: 'assets/images/pages/dientes/d5/d54/diag/ep_d54.png',
    img_extraccion: 'assets/images/pages/dientes/d5/d54/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d5/d54/diag/c_d54.png',
    img_implante: 'assets/images/pages/dientes/d5/d54/diag/i_d54.png',
    img_lesion: 'assets/images/pages/dientes/d5/d54/diag/lc_d54.png',
    img_pulpotomia: 'assets/images/pages/dientes/d5/d54/diag/p_d54.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d5/d54/diag/pp_d54.png',
    img_coronaacero: 'assets/images/pages/dientes/d5/d54/diag/cai_d54.png',
    img_coronaacetato: 'assets/images/pages/dientes/d5/d54/diag/ca_d54.png',
    img_fluoruro: 'assets/images/pages/dientes/d5/d54/diag/fp_d54.png',
    img_pulpectomia: 'assets/images/pages/dientes/d5/d54/diag/pul_d54.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d5/d54/diag/pulp_d54.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d5/d54/diag/dp_d54.png',
    img_protesisp: 'assets/images/pages/dientes/d5/d54/diag/pp.png',
  },
  {
    cod: 'd53',
    nom: '5.3',
    img_sano: 'assets/images/pages/dientes/d5/d53/diag/d53.png',
    img_endodoncia: 'assets/images/pages/dientes/d5/d53/diag/e_d53.png',
    img_endodonciap: 'assets/images/pages/dientes/d5/d53/diag/ep_d53.png',
    img_extraccion: 'assets/images/pages/dientes/d5/d53/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d5/d53/diag/c_d53.png',
    img_implante: 'assets/images/pages/dientes/d5/d53/diag/i_d53.png',
    img_lesion: 'assets/images/pages/dientes/d5/d53/diag/lc_d53.png',
    img_pulpotomia: 'assets/images/pages/dientes/d5/d53/diag/p_d53.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d5/d53/diag/pp_d53.png',
    img_coronaacero: 'assets/images/pages/dientes/d5/d53/diag/cai_d53.png',
    img_coronaacetato: 'assets/images/pages/dientes/d5/d53/diag/ca_d53.png',
    img_fluoruro: 'assets/images/pages/dientes/d5/d53/diag/fp_d53.png',
    img_pulpectomia: 'assets/images/pages/dientes/d5/d53/diag/pul_d53.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d5/d53/diag/pulp_d53.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d5/d53/diag/dp_d53.png',
    img_protesisp: 'assets/images/pages/dientes/d5/d53/diag/pp.png',
  },
  {
    cod: 'd52',
    nom: '5.2',
    img_sano: 'assets/images/pages/dientes/d5/d52/diag/d52.png',
    img_endodoncia: 'assets/images/pages/dientes/d5/d52/diag/e_d52.png',
    img_endodonciap: 'assets/images/pages/dientes/d5/d52/diag/ep_d52.png',
    img_extraccion: 'assets/images/pages/dientes/d5/d52/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d5/d52/diag/c_d52.png',
    img_implante: 'assets/images/pages/dientes/d5/d52/diag/i_d52.png',
    img_lesion: 'assets/images/pages/dientes/d5/d52/diag/lc_d52.png',
    img_pulpotomia: 'assets/images/pages/dientes/d5/d52/diag/p_d52.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d5/d52/diag/pp_d52.png',
    img_coronaacero: 'assets/images/pages/dientes/d5/d52/diag/cai_d52.png',
    img_coronaacetato: 'assets/images/pages/dientes/d5/d52/diag/ca_d52.png',
    img_fluoruro: 'assets/images/pages/dientes/d5/d52/diag/fp_d52.png',
    img_pulpectomia: 'assets/images/pages/dientes/d5/d52/diag/pul_d52.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d5/d52/diag/pulp_d52.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d5/d52/diag/dp_d52.png',
    img_protesisp: 'assets/images/pages/dientes/d5/d52/diag/pp.png',
  },
  {
    cod: 'd51',
    nom: '5.1',
    img_sano: 'assets/images/pages/dientes/d5/d51/diag/d51.png',
    img_endodoncia: 'assets/images/pages/dientes/d5/d51/diag/e_d51.png',
    img_endodonciap: 'assets/images/pages/dientes/d5/d51/diag/ep_d51.png',
    img_extraccion: 'assets/images/pages/dientes/d5/d51/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d5/d51/diag/c_d51.png',
    img_implante: 'assets/images/pages/dientes/d5/d51/diag/i_d51.png',
    img_lesion: 'assets/images/pages/dientes/d5/d51/diag/lc_d51.png',
    img_pulpotomia: 'assets/images/pages/dientes/d5/d51/diag/p_d51.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d5/d51/diag/pp_d51.png',
    img_coronaacero: 'assets/images/pages/dientes/d5/d51/diag/cai_d51.png',
    img_coronaacetato: 'assets/images/pages/dientes/d5/d51/diag/ca_d51.png',
    img_fluoruro: 'assets/images/pages/dientes/d5/d51/diag/fp_d51.png',
    img_pulpectomia: 'assets/images/pages/dientes/d5/d51/diag/pul_d51.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d5/d51/diag/pulp_d51.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d5/d51/diag/dp_d51.png',
    img_protesisp: 'assets/images/pages/dientes/d5/d51/diag/pp.png',
  },
  {
    cod: 'd61',
    nom: '6.1',
    img_sano: 'assets/images/pages/dientes/d6/d61/diag/d61.png',
    img_endodoncia: 'assets/images/pages/dientes/d6/d61/diag/e_d61.png',
    img_endodonciap: 'assets/images/pages/dientes/d6/d61/diag/ep_d61.png',
    img_extraccion: 'assets/images/pages/dientes/d6/d61/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d6/d61/diag/c_d61.png',
    img_implante: 'assets/images/pages/dientes/d6/d61/diag/i_d61.png',
    img_lesion: 'assets/images/pages/dientes/d6/d61/diag/lc_d61.png',
    img_pulpotomia: 'assets/images/pages/dientes/d6/d61/diag/p_d61.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d6/d61/diag/pp_d61.png',
    img_coronaacero: 'assets/images/pages/dientes/d6/d61/diag/cai_d61.png',
    img_coronaacetato: 'assets/images/pages/dientes/d6/d61/diag/ca_d61.png',
    img_fluoruro: 'assets/images/pages/dientes/d6/d61/diag/fp_d61.png',
    img_pulpectomia: 'assets/images/pages/dientes/d6/d61/diag/pul_d61.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d6/d61/diag/pulp_d61.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d6/d61/diag/dp_d61.png',
    img_protesisp: 'assets/images/pages/dientes/d6/d61/diag/pp.png',
  },
  {
    cod: 'd62',
    nom: '6.2',
    img_sano: 'assets/images/pages/dientes/d6/d62/diag/d62.png',
    img_endodoncia: 'assets/images/pages/dientes/d6/d62/diag/e_d62.png',
    img_endodonciap: 'assets/images/pages/dientes/d6/d62/diag/ep_d62.png',
    img_extraccion: 'assets/images/pages/dientes/d6/d62/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d6/d62/diag/c_d62.png',
    img_implante: 'assets/images/pages/dientes/d6/d62/diag/i_d62.png',
    img_lesion: 'assets/images/pages/dientes/d6/d62/diag/lc_d62.png',
    img_pulpotomia: 'assets/images/pages/dientes/d6/d62/diag/p_d62.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d6/d62/diag/pp_d62.png',
    img_coronaacero: 'assets/images/pages/dientes/d6/d62/diag/cai_d62.png',
    img_coronaacetato: 'assets/images/pages/dientes/d6/d62/diag/ca_d62.png',
    img_fluoruro: 'assets/images/pages/dientes/d6/d62/diag/fp_d62.png',
    img_pulpectomia: 'assets/images/pages/dientes/d6/d62/diag/pul_d62.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d6/d62/diag/pulp_d62.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d6/d62/diag/dp_d62.png',
    img_protesisp: 'assets/images/pages/dientes/d6/d62/diag/pp.png',
  },
  {
    cod: 'd63',
    nom: '6.3',
    img_sano: 'assets/images/pages/dientes/d6/d63/diag/d63.png',
    img_endodoncia: 'assets/images/pages/dientes/d6/d63/diag/e_d63.png',
    img_endodonciap: 'assets/images/pages/dientes/d6/d63/diag/ep_d63.png',
    img_extraccion: 'assets/images/pages/dientes/d6/d63/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d6/d63/diag/c_d63.png',
    img_implante: 'assets/images/pages/dientes/d6/d63/diag/i_d63.png',
    img_lesion: 'assets/images/pages/dientes/d6/d63/diag/lc_d63.png',
    img_pulpotomia: 'assets/images/pages/dientes/d6/d63/diag/p_d63.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d6/d63/diag/pp_d63.png',
    img_coronaacero: 'assets/images/pages/dientes/d6/d63/diag/cai_d63.png',
    img_coronaacetato: 'assets/images/pages/dientes/d6/d63/diag/ca_d63.png',
    img_fluoruro: 'assets/images/pages/dientes/d6/d63/diag/fp_d63.png',
    img_pulpectomia: 'assets/images/pages/dientes/d6/d63/diag/pul_d63.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d6/d63/diag/pulp_d63.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d6/d63/diag/dp_d63.png',
    img_protesisp: 'assets/images/pages/dientes/d6/d63/diag/pp.png',
  },
  {
    cod: 'd64',
    nom: '6.4',
    img_sano: 'assets/images/pages/dientes/d6/d64/diag/d64.png',
    img_endodoncia: 'assets/images/pages/dientes/d6/d64/diag/e_d64.png',
    img_endodonciap: 'assets/images/pages/dientes/d6/d64/diag/ep_d64.png',
    img_extraccion: 'assets/images/pages/dientes/d6/d64/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d6/d64/diag/c_d64.png',
    img_implante: 'assets/images/pages/dientes/d6/d64/diag/i_d64.png',
    img_lesion: 'assets/images/pages/dientes/d6/d64/diag/lc_d64.png',
    img_pulpotomia: 'assets/images/pages/dientes/d6/d64/diag/p_d64.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d6/d64/diag/pp_d64.png',
    img_coronaacero: 'assets/images/pages/dientes/d6/d64/diag/cai_d64.png',
    img_coronaacetato: 'assets/images/pages/dientes/d6/d64/diag/ca_d64.png',
    img_fluoruro: 'assets/images/pages/dientes/d6/d64/diag/fp_d64.png',
    img_pulpectomia: 'assets/images/pages/dientes/d6/d64/diag/pul_d64.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d6/d64/diag/pulp_d64.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d6/d64/diag/dp_d64.png',
    img_protesisp: 'assets/images/pages/dientes/d6/d64/diag/pp.png',
  },
  {
    cod: 'd65',
    nom: '6.5',
    img_sano: 'assets/images/pages/dientes/d6/d65/diag/d65.png',
    img_endodoncia: 'assets/images/pages/dientes/d6/d65/diag/e_d65.png',
    img_endodonciap: 'assets/images/pages/dientes/d6/d65/diag/ep_d65.png',
    img_extraccion: 'assets/images/pages/dientes/d6/d65/diag/cross.png',
    img_piezacoronada: 'assets/images/pages/dientes/d6/d65/diag/c_d65.png',
    img_implante: 'assets/images/pages/dientes/d6/d65/diag/i_d65.png',
    img_lesion: 'assets/images/pages/dientes/d6/d65/diag/lc_d65.png',
    img_pulpotomia: 'assets/images/pages/dientes/d6/d65/diag/p_d65.png',
    img_pulpotomiap: 'assets/images/pages/dientes/d6/d65/diag/pp_d65.png',
    img_coronaacero: 'assets/images/pages/dientes/d6/d65/diag/cai_d65.png',
    img_coronaacetato: 'assets/images/pages/dientes/d6/d65/diag/ca_d65.png',
    img_fluoruro: 'assets/images/pages/dientes/d6/d65/diag/fp_d65.png',
    img_pulpectomia: 'assets/images/pages/dientes/d6/d65/diag/pul_d65.png',
    img_pulpectomiap: 'assets/images/pages/dientes/d6/d65/diag/pulp_d65.png',
    
    img_dientepilar: 'assets/images/pages/dientes/d6/d65/diag/dp_d65.png',
    img_protesisp: 'assets/images/pages/dientes/d6/d65/diag/pp.png',
  },
  
]